adding images
Vineethaveerapu/assignment-3 pull request #22
Opened 2024-11-30 01:12 UTC by Maedeh86

add images

2024-11-30 21:15 UTC, Svpriyaa2808 reviewed
are you adding images alone

2024-12-02 09:42 UTC, Kavitha0691 reviewed
we already replace the new images in homepage sidebar and merged to develop branch. are you going to add these images in birds page?

2024-12-04 18:11 UTC, Maedeh86 commented
i want to added all sounds and images too

2024-12-06 12:09 UTC, Vineethaveerapu requested changes
i am not understanding the some part of the code, can you please tell

2024-12-06 12:09 UTC, Vineethaveerapu commented on Program.cs
why c# in javascript

2024-12-06 12:09 UTC, Vineethaveerapu commented on assignment-3.csproj
i guess this is not relevant

2024-12-06 12:09 UTC, Vineethaveerapu commented on birds.html
> +    <link rel="stylesheet" href="../assignment-3/styles/shared.css" />
i think this path are outside of project,  this will not work

2024-12-06 12:09 UTC, Vineethaveerapu commented on birds.html
> +      <aside class="sidebar">
in sub-pages you should only have birds

2024-12-06 12:09 UTC, Vineethaveerapu commented on obj/Debug/netcoreapp3.1/assignment-3.csproj.FileListAbsolute.txt
can you update gitignore and debug and bin

2024-12-08 12:00 UTC, Vineethaveerapu approved these changes
sidebar and main content is working

2024-12-08 12:01 UTC, merged